# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: bznein
google_analytics: dbyll
title: Bznein's

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Bznein's

description: A.K.A. Deggio
author:
  name: Nikolas De Giorgis
  email: nikolas.degiorgis@gmail.com
  github: bznein
  twitter: bznein
  linkedin: nikolas-de-giorgis
  bio: Basically, a software developer. Less basically, I'm passionate about photography, music, sport, reading, traveling and many, many other things!
  email_md5: 544578746546bb28aeeb2c86b8c6cf96

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
